mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: edu.dzkj.cloud.mybatisx.entity
  # MyBatis-Plus的配置文件，如果有的话
  config-location: classpath:mybatis-config.xml

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hello_mp?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: edu.dzkj.cloud.mybatisx.entity

